name : "cd React CI-CD Workflow"
on:
  workflow_run:
    workflows: ["sample React CI-CD Workflow"]
    types:
      - completed
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
        - name: "Setup Node.js environment"
          uses: actions/setup-node@v4
          with:
            node-version: '21'
        - name: "setup versel cli"
          run: npm install -g vercel
        - name: "download artifacts"
          uses: actions/download-artifact@v4
          with:
            name: build
        - name: "Download build files"
          uses: actions/download-artifact@v4
          with:
            name: build
            run-id: ${{ github.event.workflow_run.id }}
            github-token: ${{ github.token }}

        - name: "Deploy to vercel"
          run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name="react-cicd-demo"